[package]
name = "lambda_fairy"
version = "1.0.0"
edition = "2018"

[dependencies]
anyhow = "*"
chrono = "*"
comrak = "*"
itertools = "*"
once_cell = "*"
maud = "*"
syntect = "*"

[profile.dev.package."*"]
opt-level = 2
